<a href="https://colab.research.google.com/github/wahajal1/student_grades_anlysis/blob/main/Student_%20Grades.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("students_scores.csv")

In [3]:
df.head()

   StudentID     Name  Math  Science  English
0          1    Alice    85       78       92
1          2      Bob    76       81       85
2          3  Charlie    90       89       95
3          4    Diana    66       74       70
4          5     Evan    95       92       88

In [5]:
df.shape

(5, 5)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   StudentID  5 non-null      int64
 1   Name       5 non-null      object
 2   Math       5 non-null      int64
 3   Science    5 non-null      int64
 4   English    5 non-null      int64
dtypes: int64(4), object(1)
memory usage: 332.0+ bytes

In [7]:
df.describe()

       StudentID       Math   Science    English
count   5.000000   5.000000   5.00000   5.000000
mean    3.000000  82.400000  82.80000  86.000000
std     1.581139  11.545562   7.52994   9.721111
min     1.000000  66.000000  74.00000  70.000000
25%     2.000000  76.000000  78.00000  85.000000
50%     3.000000  85.000000  81.00000  88.000000
75%     4.000000  90.000000  89.00000  92.000000
max     5.000000  95.000000  92.00000  95.000000

In [8]:
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1)

print(df[['Name', 'Average']])

      Name    Average
0    Alice  85.000000
1      Bob  80.666667
2  Charlie  91.333333
3    Diana  70.000000
4     Evan  91.666667

In [18]:
# Find the highest score in each subject and the student who achieved it
math_max = df.loc[df['Math'].idxmax()] #whats inside df.loc returns the highest grade in math but its index
#then df.loc finds that student with the same index
science_max = df.loc[df['Science'].idxmax()]
english_max = df.loc[df['English'].idxmax()]
# Clean and readable output
print(f"Highest score in Math: {math_max['Name']} with {math_max['Math']}")
print(f"Highest score in Science: {science_max['Name']} with {science_max['Science']}")
print(f"Highest score in English: {english_max['Name']} with {english_max['English']}")

Highest score in Math: Evan with 95
Highest score in Science: Evan with 92
Highest score in English: Charlie with 95

In [19]:
# Sort the students by their overall average score (highest first)
df['Average'] = df[['Math', 'Science', 'English']].mean(axis=1) #caculates the average of the 3 subjects, axis=1 means cacualting on rows
top_3_students = df.sort_values(by='Average', ascending=False).head(3) #sort them descending

print("Top 3 students by average score:")
print(top_3_students[['Name', 'Average']])

Top 3 students by average score:
      Name    Average
4     Evan  91.666667
2  Charlie  91.333333
0    Alice  85.000000

In [13]:
# List students who scored more than 80 in Math
students_above_80_math = df[df['Math'] > 80]#generates a new dataframe with only the students who scored higher than 80

print("Students who scored above 80 in Math:")
print(students_above_80_math[['Name', 'Math']])

Students who scored above 80 in Math:
      Name  Math
0    Alice    85
2  Charlie    90
4     Evan    95

In [14]:
# Calculate the total score (sum of Math, Science, and English) for each student
df['Total'] = df[['Math', 'Science', 'English']].sum(axis=1)

print("Total score for each student:")
print(df[['Name', 'Total']])

Total score for each student:
      Name  Total
0    Alice    255
1      Bob    242
2  Charlie    274
3    Diana    210
4     Evan    275

In [20]:
# Create a column that compares English and Science scores
df['Better Subject'] = df.apply(lambda row: 'English' if row['English'] > row['Science'] else 'Science', axis=1)
#df.apply does the function on each row in the dataframe, lamda acts like an anonmyous function
'''
creating the function normally:
def better_subject(row):
    if row['English'] > row['Science']:
        return 'English'
    else:
        return 'Science'

# تطبيق الدالة على كل صف باستخدام apply()
df['Better Subject'] = df.apply(better_subject, axis=1)
'''
print("Comparison between English and Science scores:")
print(df[['Name', 'English', 'Science', 'Better Subject']])

Comparison between English and Science scores:
      Name  English  Science Better Subject
0    Alice       92       78        English
1      Bob       85       81        English
2  Charlie       95       89        English
3    Diana       70       74        Science
4     Evan       88       92        Science